const fs = require('fs');

let content = fs.readFileSync('src/components/home/HomeContent.tsx', 'utf-8');

const oldBlock = `<div class="client-stack">\\n          <ul>\\n          <li>\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/react" alt="React" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block;"></picture>\\n          </li>\\n          <li>\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/nextdotjs/000000" alt="Next.js" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block;"></picture>\\n          </li>\\n          <li>\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/vercel/000000" alt="Vercel" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block;"></picture>\\n          </li>\\n          <li>\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/stripe" alt="Stripe" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block;"></picture>\\n          </li>\\n          <li>\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/github/000000" alt="GitHub" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block;"></picture>\\n          </li>\\n          <li>\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/figma" alt="Figma" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block;"></picture>\\n          </li>\\n          <li>\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/amazonwebservices/232F3E" alt="AWS" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block;"></picture>\\n          </li>\\n          <li>\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/googlecloud" alt="Google Cloud" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block;"></picture>\\n          </li>\\n          </ul>\\n        </div>`;

const newBlock = `<div class="client-stack" style="margin-top: 30px;">\\n          <ul style="display: flex; flex-wrap: wrap; gap: 20px; align-items: center; justify-content: flex-start; list-style: none; padding: 0;">\\n          <li style="flex: 0 0 calc(25% - 20px); display: flex; justify-content: center; align-items: center;">\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/react" alt="React" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block; opacity: 0.8;"></picture>\\n          </li>\\n          <li style="flex: 0 0 calc(25% - 20px); display: flex; justify-content: center; align-items: center;">\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/nextdotjs/000000" alt="Next.js" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block; opacity: 0.8;"></picture>\\n          </li>\\n          <li style="flex: 0 0 calc(25% - 20px); display: flex; justify-content: center; align-items: center;">\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/vercel/000000" alt="Vercel" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block; opacity: 0.8;"></picture>\\n          </li>\\n          <li style="flex: 0 0 calc(25% - 20px); display: flex; justify-content: center; align-items: center;">\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/stripe" alt="Stripe" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block; opacity: 0.8;"></picture>\\n          </li>\\n          <li style="flex: 0 0 calc(25% - 20px); display: flex; justify-content: center; align-items: center;">\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/github/000000" alt="GitHub" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block; opacity: 0.8;"></picture>\\n          </li>\\n          <li style="flex: 0 0 calc(25% - 20px); display: flex; justify-content: center; align-items: center;">\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/figma" alt="Figma" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block; opacity: 0.8;"></picture>\\n          </li>\\n          <li style="flex: 0 0 calc(25% - 20px); display: flex; justify-content: center; align-items: center;">\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/apple/000000" alt="Apple" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block; opacity: 0.8;"></picture>\\n          </li>\\n          <li style="flex: 0 0 calc(25% - 20px); display: flex; justify-content: center; align-items: center;">\\n          <picture><img loading="lazy" src="https://cdn.simpleicons.org/googlecloud" alt="Google Cloud" width="50" height="50" style="object-fit: contain; margin: 0 auto; display: block; opacity: 0.8;"></picture>\\n          </li>\\n          </ul>\\n        </div>`;

content = content.replace(oldBlock, newBlock);

fs.writeFileSync('src/components/home/HomeContent.tsx', content);
console.log('done');
